---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.13

inputs:
- name: credhub-resource

outputs:
- name: built-binaries

run:
  path: credhub-resource/ci/tasks/build.sh
