---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
- name: credhub-resource

outputs:
- name: built-binaries

run:
  path: credhub-resource/ci/tasks/build.sh
