---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
- name: credhub_resource

run:
  path: credhub_resource/ci/tasks/lint.sh
