---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
- name: interpolated_credhub_resource_ci

run:
  path: interpolated_credhub_resource_ci/tasks/systest_get_updated_credential.sh

params:
  CREDHUB_SERVER: 
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_CA_CERT:
  SKIP_TLS_VALIDATION:
  CONCOURSE_URL:
  CONCOURSE_USERNAME:
  CONCOURSE_PASSWORD: 