---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
- name: credhub-resource

run:
  path: credhub-resource/ci/tasks/unit-test.sh
