---
resources:
- name: credhub_resource
  type: git
  source:
    branch: master
    uri: git@github.com:EngineerBetter/credhub-resource.git
    private_key: ((github_private_key))

jobs:
- name: test
  plan:
  - get: credhub_resource
    trigger: true
  - task: lint
    file: credhub_resource/ci/tasks/lint.yml
  - task: unit-test
    file: credhub_resource/ci/tasks/unit-test.yml

- name: rc
  serial_groups: [version]
  plan:
  - get: credhub_resource
    passed: [test]
    trigger: true
  - task: build
    file: credhub_resource/ci/tasks/build.yml